//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CPHAirport
{
    using System;
    using System.Collections.Generic;
    
    public partial class flightroute
    {
        public int flightRouteID { get; set; }
        public int destination { get; set; }
        public int departure { get; set; }
        public string flightCompany { get; set; }
        public int planeID { get; set; }
    
        public virtual location location { get; set; }
        public virtual location location1 { get; set; }
        public virtual plane plane { get; set; }
    }
}
