//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CPHAirport
{
    using System;
    using System.Collections.Generic;
    
    public partial class plane
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public plane()
        {
            this.flightroutes = new HashSet<flightroute>();
        }
    
        public int planeID { get; set; }
        public int passengerCapacity { get; set; }
        public int aproxMinReachInKm { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<flightroute> flightroutes { get; set; }
    }
}
